# Generated by Django 5.1.3 on 2025-01-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ticketreservations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketreservations',
            name='End_Date',
        ),
        migrations.RemoveField(
            model_name='ticketreservations',
            name='Start_Date',
        ),
    ]
