# Generated by Django 5.1.3 on 2025-01-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_ticketreservations_end_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketReservations',
            new_name='TicketReserve',
        ),
    ]
