# Generated by Django 5.1.3 on 2025-01-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_ticketreservations_ticketreserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreserve',
            name='Ticket_type',
            field=models.CharField(default='Adult', max_length=15),
            preserve_default=False,
        ),
    ]
