# Generated by Django 5.1.3 on 2025-01-22 12:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ticketreserve_ticket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketreserve',
            name='id',
        ),
        migrations.AlterField(
            model_name='ticketreserve',
            name='Ticket_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
