# Generated by Django 5.1.3 on 2025-01-27 09:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_ticketreserve_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelReserve',
            fields=[
                ('User_id', models.CharField(max_length=5000)),
                ('RoomKey_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Room_type', models.CharField(max_length=100)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
            ],
        ),
    ]
